[project]
name = "dot_vault"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.12.4",
    "result>=0.17.0",
]

[dependency-groups]
dev = [
    "hatch>=1.15.1",
    "pytest-cov>=7.0.0",
]

[tool.pytest.ini_options]
pythonpath = ["src/"]

[tool.hatch.envs.default.scripts]
test = "pytest --cov=dot_vault src/tests/"
testlog = """
    pytest \
        --no-header \
        --log-level=DEBUG --log-cli-level=DEBUG \
        --capture=no \
        src/tests/{args}
"""
